const questions_2 = {
  lovers: [
    "What is my love language?",
    "What's one thing I do that makes you smile?",
    "What was our first date?",
    "What food reminds you of me?",
    "What's my idea of a perfect romantic evening?",
    "What's the first thing you noticed about me?",
    "How do I show I care when words aren't enough?",
    "What small habit of mine do you secretly love?",
    "What's my favorite thing about being with you?",
    "If we could go anywhere together right now, where would I choose?",
    "What's a song that reminds you of our relationship?",
    "What do you think I dream about most often?",
    "When did you know you were in love with me?",
    "What's something I do that always makes you feel safe?",
    "What's my favorite way to spend a lazy day with you?",
    "What do you think is my favorite memory of us?",
    "How do I comfort you when you're sad?",
    "What's something we both love doing together?",
    "What kind of future do you think I imagine with you?",
    "What's one thing you'd never change about me?",
    "What's a place I've always wanted to go with you?",
    "What's one inside joke we always laugh at?",
    "What's one thing you've learned from our relationship?",
    "How do I act when I'm jealous?",
    "What's a pet name or nickname I secretly love?",
    "What would our dream home look like?",
    "What's one thing I've said that really stayed with you?",
    "What do I think is your most attractive quality?",
    "If I were an animal, which one would I be?",
    "What's one small thing I do that shows I'm thinking of you?",
    "What's my favorite time of day to spend with you?",
    "What's one tradition you'd like to start with me?",
    "What do I value most in our relationship?",
    "How would I describe our first kiss?",
    "What's one thing I've done that surprised you (in a good way)?",
    "When do I miss you the most?",
    "How do I react when I'm really proud of you?",
    "What's one thing we've been through that made us stronger?",
    "What does my ideal weekend look like?",
    "How do I flirt when I'm being playful?",
    "If we could relive one day together, what would it be?",
    "What's something I want us to do more often?",
    "What kind of date do I secretly wish you'd plan?",
    "How do I usually express affection?",
    "What's my favorite way you touch me?",
    "What's one movie or show that reminds me of us?",
    "If I could cook one meal for us, what would it be?",
    "What's one way I make you feel appreciated?",
    "When do I feel most loved by you?",
    "What's something we haven't done yet but I'd love to try together?",
    "If I wrote you a love letter, what would it start with?",
    "What do I do that makes you feel most seen?",
    "What's one silly thing we argue about?",
    "What's a small gesture from you that makes my whole day?",
    "What's my guilty pleasure?",
    "How do I handle conflict in our relationship?",
    "What's something I only do when I'm around you?",
    "What kind of couple do you think we'll be in 20 years?",
    "What's my favorite compliment you've ever given me?",
    "What would I do if I had one day to spoil you completely?"
  ],
  bestFriends: [
    "What's our most legendary moment together?",
    "What's my favorite inside joke of ours?",
    "Which game or show do I never shut up about?",
    "If I had to pick a theme song, what would it be?",
    "What's my most annoying habit you've learned to love?",
    "What food do I always order when we hang out?",
    "Who do I always complain about?",
    "What's my dream job?",
    "Which meme perfectly describes me?",
    "What's one secret you think only I know about you?",
    "What's one thing I always say that's so me?",
    "If I got famous, what would it be for?",
    "What's a memory that always makes us laugh?",
    "Who do I always stalk on social media?",
    "What's something I can never say no to?",
    "What was my biggest phase growing up?",
    "What's my weirdest food combo that I actually love?",
    "What's one word you'd use to describe me?",
    "Which fictional character do I act like the most?",
    "What's something I always forget, no matter how many times I'm reminded?",
    "If I ran away, where would I go?",
    "What's my go-to comfort movie or show?",
    "What's something I'm surprisingly good at?",
    "What's my worst fashion crime ever?",
    "What was our most random but iconic conversation?",
    "If I were a villain, what would my evil plan be?",
    "What's my toxic trait (in a funny way)?",
    "What's the dumbest fight we've ever had?",
    "If I were an emoji, which one would I be?",
    "What's the most dramatic thing I've ever done?",
    "What's my “I'm bored” activity?",
    "What's one thing I'll defend with my life?",
    "What kind of friend am I in the group?",
    "What's something I always overthink?",
    "What's my favorite excuse for not replying fast?",
    "Which trend or app am I most addicted to?",
    "What do I always hype you up for?",
    "What's a weird challenge we should try together?",
    "What's a tradition we've accidentally created?",
    "What's the dumbest way we've wasted time together?",
    "What's a song that's totally our vibe?",
    "What's something I say when I'm lying?",
    "If I had a personal logo, what would it be?",
    "What's a conspiracy theory I'd totally believe in?",
    "What's my go-to comfort snack?",
    "What do I always rant about?",
    "If we switched lives for a day, what's the first thing I'd do?",
    "What's one thing only you can roast me for?",
    "What's something I do when I'm nervous?",
    "If we had a reality show, what would it be called?",
    "What do I always take too seriously?",
    "What do I do that instantly gives away my mood?",
    "If I was a game character, what would my special power be?",
    "What's my biggest fear (that's kinda irrational)?",
    "What's one thing you'd trust me to do in a crisis?",
    "What's the most me-thing I've ever done?",
    "What's one word that would ruin my whole day?",
    "If I were a flavor, what would I be?",
    "What's something you hope I never change?",
    "If we made a bucket list, what would be #1?"
],
 momOrDad: [
    "What was the favorite cartoon during childhood?",
    "What food was hated the most growing up?",
    "Which toy was the biggest obsession as a kid?",
    "What school subject was the most fun?",
    "What was a common childhood fear?",
    "What was a weird habit from childhood?",
    "What's a habit from childhood that still exists today?",
    "What would usually be said when angry as a kid?",
    "Who was the childhood best friend?",
    "What was the dream job growing up?",
    "What's a family tradition that means the most?",
    "Who was stricter growing up — Mom or Dad?",
    "What's a song that reminds you of family time?",
    "What's the first trip we ever took together?",
    "What's something we always did on weekends?",
    "What's one thing we always argue about but still laugh later?",
    "What's something silly we both believed as kids?",
    "What's the biggest mess you remember cleaning up for me (or vice versa)?",
    "What's one thing we both secretly love but never admit out loud?",
    "What's the most embarrassing story we tell each other about childhood?",
    "What's something I got from your personality?",
    "What's a habit or phrase we both use without realizing?",
    "Who's more emotional — me or you?",
    "What's the most memorable birthday celebration we had together?",
    "What's a recipe or food that instantly reminds you of home?",
    "What's something you wish we did more when I was younger (or now)?",
    "What's one family rule I always broke (or you always let slide)?",
    "What's the funniest misunderstanding we've had?",
    "What was my favorite hiding spot as a kid (or yours)?",
    "What's one movie we've watched too many times together?",
    "What's the best piece of advice you've given (or received from me)?",
    "What's a skill or talent we both share?",
    "What's something you never told me about your childhood?",
    "What's a smell that brings back childhood memories?",
    "What's something I did as a kid that made you really proud (or vice versa)?",
    "Who's the better storyteller between us?",
    "What's the funniest lie I ever told as a kid (or you told your parents)?",
    "What's something we always bond over?",
    "What's one thing we always disagree on but still respect?",
    "What's the most surprising thing we've learned about each other?",
    "What was your biggest dream as a kid (or mine)?",
    "What's something you did for me that I probably didn't understand back then?",
    "What's the worst haircut I ever had (or you had)?",
    "What's a phrase you always say and I've started using too?",
    "Who was the more mischievous kid — me or you?",
    "What's something I used to cry about that's funny now?",
    "What's one time we laughed so hard we cried?",
    "What's something you wish I understood earlier (or vice versa)?",
    "What's a favorite item we always kept — even if old or broken?",
    "What's the most valuable lesson we've learned from each other?",
    "What's something I said as a kid that you still remember?",
    "What's a childhood game we should play again together?",
    "Who's more dramatic in the family — you or me?",
    "What's something that always made (or makes) us feel better after a bad day?",
    "What's the first big mistake I made — and how did we handle it?",
    "What's a joke we've shared for years?",
    "What's something you always did to make me feel better (or I did for you)?",
    "What's a moment when you felt truly proud of me (or I felt proud of you)?",
    "What's something we should do more now to make new memories?",
    "What's the thing that connects us most, no matter how much time passes?"
  ],
  bros: [
    "Who's stronger - you or me?",
    "What's our go-to game together?",
    "What was the dumbest thing we did together?",
    "Who would survive a zombie apocalypse longer?",
    "If we started a band, what would we call it?",
    "What's one word I always overuse?",
    "What's my dream car?",
    "What's the one joke I never let die?",
    "What was the last fight we had about?",
    "Which superhero would I be?",
    "What's the most epic prank we've pulled (or planned)?",
    "What's my go-to move in a fight (real or game)?",
    "What food do I always steal off your plate?",
    "What's one secret we've sworn never to tell?",
    "What's the weirdest nickname we've ever used?",
    "What's one thing we always compete over?",
    "What's my weirdest flex?",
    "Who would rage-quit first in a co-op game?",
    "What's the most legendary comeback I've ever made?",
    "What's a movie we've watched way too many times?",
    "What's one thing I always blame you for (even when it's my fault)?",
    "What's the stupidest dare I ever took seriously?",
    "What's my trash talk line?",
    "What's one thing I always deny doing?",
    "What would be our WWE tag team name?",
    "What's my ultimate snack combo?",
    "Who would win in a rap battle between us?",
    "What's a trend I totally rocked (or failed at)?",
    "What's one thing I always lose and you always find?",
    "What's the dumbest thing we argued about and still remember?",
    "What's my most used emoji?",
    "If I became a villain, what would my evil plan be?",
    "What's the worst fashion choice I've ever made?",
    "Who's more likely to get arrested — and why?",
    "What's my secret weapon in any challenge?",
    "If we had a YouTube channel, what would it be about?",
    "What's the most random inside joke we have?",
    "Who gives the worst advice — me or you?",
    "What's my most shameless guilty pleasure?",
    "What's the biggest risk we've ever taken together?",
    "What's something only you know I'm low-key scared of?",
    "What's the fastest way to annoy me?",
    "What's my zombie apocalypse weapon of choice?",
    "If I had a warning label, what would it say?",
    "What's the weirdest bro challenge we ever accepted?",
    "Who's more dramatic in real life (be honest)?",
    "What's something I always say when I lose?",
    "What's my most iconic insult?",
    "What's the best roast you've ever hit me with?",
    "If I went viral, what would it be for?",
    "What's the most random thing we've done at 2am?",
    "What's a song we both secretly love but never admit?",
    "What's one thing we'd dominate in as a team?",
    "Who's more likely to start a fight over food?",
    "What's a line I say way too often?",
    "What's something we both suck at but still try anyway?",
    "Who has more main-character energy?",
    "What's my default panic move when things go wrong?",
    "What's the bro code rule we both broke?",
    "What's one thing we should never do again?"
  ],
  sisters: [
    "What's the one outfit I loved way too much?",
    "What secret of mine have you kept?",
    "What's the song I always sing out loud?",
    "What's the one thing I never share?",
    "Which celebrity crush did I never get over?",
    "What's my go-to comfort snack?",
    "Which romcom would I force you to watch again?",
    "What's the dumbest fight we had?",
    "What do I do when I get sad?",
    "What's something I can never live without?",
    "What's one trend I was obsessed with?",
    "What's the most dramatic thing I've ever said?",
    `What's my "I'm not okay but I'll say I'm fine" face?`,
    "What's my guilty pleasure show or movie?",
    "What's something we always bond over?",
    "What's one thing I never leave the house without?",
    "What would I wear if I had 5 minutes to get ready?",
    "What's the most iconic sister moment we've had?",
    "What's one phrase I say way too much?",
    "Who's the bigger drama queen — you or me?",
    "What's something we both secretly love but never admit out loud?",
    "What's one lie we've both told and kept up?",
    "What's my worst fashion mistake ever?",
    "If I had a personal theme song, what would it be?",
    "What's my favorite comfort movie on a bad day?",
    "What's one outfit I'd wear every day if I could?",
    "What do I always do when I like someone?",
    "What's something I always complain about?",
    "What's one thing I always hype you up for?",
    "What's a moment we always laugh about, no matter how many times we tell it?",
    "What's one thing I'd cry over but laugh about later?",
    "What's my ideal weekend vibe?",
    "Who's more likely to win a dance battle between us?",
    "What's my ultimate go-to revenge plan (even if I never use it)?",
    "What's one thing I always overthink?",
    "What's something we both know we'd fight over immediately?",
    "What's a dream we both share?",
    "What's something I say that always means I'm mad?",
    "What's one thing I always borrow and never return?",
    "What's something we should've gotten in trouble for — but didn't?",
    "What's a song that instantly gives us a flashback?",
    "What's one thing I've always wanted to try but never had the courage?",
    "What's my midnight craving snack?",
    "What's something we used to argue about that's funny now?",
    "What do I do when I try to act cool but totally fail?",
    "What's something you've never told me but know I'd laugh at?",
    "What's my fake excuse for not going out?",
    "What's the one time I was totally right and wouldn't shut up about it?",
    "What would my aesthetic be if I was a Pinterest board?",
    "What's my most iconic comeback or clapback?",
    "What's one weird thing I'm obsessed with?",
    "What's something that would instantly make me feel better?",
    "What's the most emotional thing I've ever told you?",
    "What's one thing I'll defend no matter what?",
    "What would we name our imaginary business or shop?",
    "What's a phrase we always say that no one else understands?",
    "What's the moment you knew we'd always be close?",
    "Who apologizes first after a fight — me or you?",
    "What's a goal I've always had but haven't reached (yet)?",
    "What's a part of my personality people don't always see?"
  ],
  roommates: [
    "Who's the messier one?",
    "What's my weirdest habit at home?",
    "What's the most annoying thing I do in the kitchen?",
    "What's my midnight snack of choice?",
    "What's one thing I always forget to do?",
    "Which one of us always uses up the WiFi?",
    "What song do I play too loud?",
    "What's the worst chore for me?",
    "What's one household rule I always break?",
    "What's the weirdest thing you've caught me doing?",
    "What's my go-to excuse for avoiding chores?",
    "What's something you always have to remind me to do?",
    "What's my worst cleaning habit?",
    "If I vanished for a day, where would I most likely be?",
    "What's the most random thing I've ever ordered online?",
    "What's the one smell that instantly says ‘I'm cooking again'?",
    "Who's more likely to start a dance party at 11 PM?",
    "What's the biggest mess I've ever left behind?",
    "What's something I do that screams ‘main character energy'?",
    "What's the one thing I always borrow without asking?",
    "What's my signature bathroom habit?",
    "What's my ‘I'm stressed out' behavior?",
    "What's something in the apartment that I treat like it's sacred?",
    "What's the weirdest thing in my fridge?",
    "If we had a house anthem, what would it be?",
    "What's one roommate rule I made but never follow?",
    "What's something I do that always makes you roll your eyes?",
    "Who would survive a solo camping trip — me or you?",
    "What's one thing in the house I should never be trusted with?",
    "What's my laziest hack for getting things done?",
    "What's my most repeated rant?",
    "What's something I do that could be a TikTok trend (or fail)?",
    "What's the strangest noise I make when no one's around?",
    "What chore would I actually pay someone else to do?",
    "What's the weirdest way I've taken out the trash?",
    "What's one thing I always forget at the grocery store?",
    "What's something I pretend I know how to do, but totally don't?",
    "What's my most random daily ritual?",
    "What's something we should *definitely* not do together again?",
    "What's my go-to “I don't want to talk right now” move?",
    "What's one thing in the house that triggers my drama?",
    "What's the last time I shocked you with responsibility?",
    "What's my 'I just woke up' mood like?",
    "What's one item of mine that should've been thrown out ages ago?",
    "What do I always say when the rent is due?",
    "What's my kitchen crime you've learned to live with?",
    "What's my emotional support snack?",
    "What's my most overused complaint about the house?",
    "What's my idea of a ‘deep clean' vs yours?",
    "What's something in this apartment I absolutely baby?",
    "What's my weirdest midnight activity you've caught?",
    "What's something I've sworn I'd fix, but never did?",
    "What's my go-to way to procrastinate cleaning?",
    "What's a guilty pleasure I always try to hide?",
    "What do I do when I think I'm home alone?",
    "What's one thing you admire about how I live (even if it's chaotic)?",
    "Who's more likely to start a fight over dish soap?",
    "If we made a roommate survival guide, what would be rule #1?",
    "What's one thing we both silently agree to never bring up?",
    "What's something you'd miss if I ever moved out?"
  ],
  workBuddies: [
    "What's my favorite excuse to leave early?",
    "What task do I hate the most?",
    "Which coworker do I talk about the most?",
    "What snack is always at my desk?",
    "What's the first thing I do when I log in?",
    "What meeting do I always try to skip?",
    "What's the worst office drama I've ranted about?",
    "What's the one job I'd quit this for?",
    "What's my guilty pleasure during work hours?",
    "What's the nickname I secretly gave our boss?",
    `What's my go-to fake "I'm busy" face?`,
    "What's the one phrase I say too much during meetings?",
    "What's my unofficial role in the team?",
    "What's something I pretend to understand but secretly don't?",
    "What's my most used emoji in work chats?",
    "What's the first thing I complain about every morning?",
    "What's my most chaotic moment at work so far?",
    "What's the one tab I always have open (that's not work)?",
    "What song do I play when I'm trying to focus?",
    "What's one app or tool I absolutely hate using?",
    "Who do I always ask for help before asking the manager?",
    "What's my go-to caffeine source during crunch time?",
    "What's something I always forget before a meeting?",
    "What's my low-key side hustle idea?",
    `What's one file I've "accidentally" deleted or lost?`,
    `What's my favorite "I'm totally working" posture?`,
    "What's the one project I never want to be assigned again?",
    "What's the longest break I've turned into a “quick 5 minutes”?",
    "What's something I'd totally automate if I could?",
    `What's my default response when someone says "urgent"?`,
    "What's the weirdest thing I've ever eaten at my desk?",
    "Who do I always gossip with during lunch?",
    "What's one thing I always complain about in our software?",
    "What's my favorite work-avoidance ritual?",
    "What's the most random thing I've done during a video call?",
    "What's something I always leave till the last minute?",
    "What's one task I weirdly enjoy (but don't admit)?",
    `What's the most "me" background I've used on Zoom/Meet?`,
    `What's my "I'm about to log off early" behavior?`,
    "What's the one notification I always ignore?",
    "What's a skill I totally exaggerated on my resume?",
    "What's something I secretly hope gets canceled every week?",
    `What's my ultimate "fake productivity" move?`,
    "What's the one thing guaranteed to distract me mid-task?",
    "What's the biggest lie I've told in a status update?",
    `What's the most "I've given up" thing I've worn to a meeting?`,
    `What's something I do that screams "It's Friday!"?`,
    "What's a weird desktop wallpaper I once had?",
    "What's my go-to motivational line (even if I don't believe it)?",
    "What's the most random Slack/Teams/Discord channel I'm active in?",
    "What's my biggest keyboard shortcut flex?",
    "What's one part of the job I totally zone out during?",
    "What's my secret talent that has nothing to do with work?",
    "What's the snack I hoard and never share?",
    `What's one "work from home" excuse I definitely overuse?`,
    "What's the weirdest thing I've done during a boring call?",
    "What's my go-to rant when I've had a long day?",
    "What's something I always say I'll do tomorrow, but never do?",
    "What's one thing I do that makes it obvious I want to go home?",
    "What's my dream job if money didn't matter?",
    "What's one thing you'd miss if I left the company?"
  ],
  newlyweds: [
    "What side of the bed do I sleep on?",
    "What's my worst kitchen habit?",
    "What's our biggest difference so far?",
    "What's the first thing I do when I wake up?",
    "What chore do I always avoid?",
    "What's one thing I never leave the house without?",
    "What's my favorite part of being married?",
    "What's my most annoying newlywed habit?",
    "What word do I use too much?",
    "What's something we still argue about?",
    "What's my go-to comfort food after a rough day?",
    "What's one thing I do that always makes you smile?",
    `Who usually says "sorry" first after an argument?`,
    "What's the weirdest house rule we've made up?",
    "What's something you still don't fully understand about me?",
    "What's one household item I treat like treasure?",
    "What's my idea of a perfect date night at home?",
    "What's something I do that instantly tells you I'm in a bad mood?",
    "What's one thing you've learned about me that surprised you?",
    "What's my weirdest bedtime ritual?",
    "What's the chore I pretend not to see?",
    `What's my version of "cleaning the house"?`,
    "What's the funniest moment we've had since the wedding?",
    "What's my favorite way to celebrate small wins?",
    "What's a small gesture I do that shows I love you?",
    "What's my most dramatic reaction to something minor?",
    "What's something I do when I think no one's watching?",
    "What's a goal I talk about all the time?",
    "What's the most random thing we've bought together?",
    "What's a food I claimed to love before marriage… but don't really?",
    "What's a word or phrase we've both picked up from each other?",
    "What's my guilty pleasure TV show or movie?",
    "What's something we still haven't figured out how to do together?",
    "What's one habit of mine you secretly find cute?",
    "What's something I always forget, no matter how many times I'm reminded?",
    "Who's more likely to cry during a movie?",
    "What's the most couple-y thing we do that would make our single friends cringe?",
    "What's something I do that makes you laugh when you shouldn't?",
    "What's one topic we always go in circles about?",
    "What's the pet name I use the most?",
    "What's something I always misplace?",
    "What's the first thing I do when we get home from an outing?",
    "What's my idea of relaxing vs yours?",
    "What's something I'm overly picky about?",
    "What's a household thing I always try to fix but make worse?",
    "What's the last thing I said that made you roll your eyes?",
    "What's my ultimate comfort outfit at home?",
    "What's something we've agreed to disagree on?",
    "What's one romantic thing I do without even realizing it?",
    "What's a future plan I bring up constantly?",
    `What's the most "married couple" thing we've done so far?`,
    "What's something I do when I want your attention?",
    `What's a store or aisle I get "lost" in every time?`,
    "What's my favorite time of day to be with you?",
    "What's one thing I still call by the wrong name?",
    "What's a habit of yours I've started copying?",
    `What's my ultimate "I'm too tired to cook" meal?`,
    "What's one thing that instantly makes me feel better after a fight?",
    "What's something we both swore we'd never do — but now totally do?",
    "What's something you think I love more than you (just barely)?",
    "What's the best surprise I've given you since the wedding?"
  ],
  marriedCouple: [
    "What is one tradition we've kept over the years?",
    "What's the most memorable trip we've taken together?",
    "What do we still argue about after all these years?",
    "What's a habit I've never grown out of?",
    "What is one thing that still surprises you about me?",
    "What's something we always laugh about?",
    "What song has become 'our song' over time?",
    "What do we do best as a team?",
    "What's one goal we still want to achieve together?",
    "What's one thing we've overcome as a couple that made us stronger?",
    "What's a habit of mine you've learned to love over the years?",
    "What's one thing we do that always brings us closer?",
    "What's something we used to do more of that we should bring back?",
    "What's one major decision we absolutely nailed together?",
    "What's the most thoughtful thing I've done that you'll never forget?",
    `What's the most "us" thing we do without realizing it?`,
    "What's something small that still makes me feel loved?",
    "What do I always do when I'm trying to avoid an argument?",
    "What's something we always do before bed — even if we're tired?",
    "What's a disagreement that taught us a lot about each other?",
    `What's one place that feels like "our spot"?`,
    "What's something we both swore we'd never do, but now we do often?",
    "What's the most embarrassing moment we've shared — and now laugh at?",
    "What's one routine that makes our relationship stronger?",
    "What's a change we've made that improved our relationship?",
    "What's something I do when I'm really trying to make you smile?",
    "What's a piece of advice we'd give to new couples?",
    "What's something I used to do that you miss?",
    "What's my favorite way to show affection?",
    "What's something I say that still melts your heart?",
    "What's one moment that tested our patience but brought us closer?",
    "What's something only we understand about each other?",
    "What's something I do that always calms you down?",
    "What's a financial decision we made that paid off?",
    "What's a goal we achieved that once felt impossible?",
    "What's something you've learned from me that changed how you think?",
    "What's my most stubborn opinion — and do you secretly agree with it?",
    "What's something we never agree on, but have learned to respect?",
    "What's a phrase or inside joke we still use after all this time?",
    "What's something I do when I'm feeling nostalgic?",
    "What's something that used to bother you but now you find endearing?",
    "What's one of our most underrated accomplishments as a couple?",
    "What's something I do when I want your attention — but won't admit it?",
    "What's our best decision during a stressful time?",
    "What's a memory that still feels like it happened yesterday?",
    "What's a moment where we couldn't stop laughing together?",
    "What's a challenge we faced that brought out the best in us?",
    "What's my favorite part of growing old with you?",
    "What's a simple moment that perfectly defines ‘us'?",
    "What's one big dream we still talk about?",
    "What's something in our daily routine that I secretly love?",
    "What's one tradition we unintentionally started?",
    "What's something we're better at now than we were in year one?",
    "What's one word or phrase that perfectly sums up our relationship?",
    "What's a song, movie, or show that's become our comfort content?",
    "What's a trait of mine you didn't appreciate at first but now love?",
    "What's something we both used to care about that we now laugh off?",
    "What's one thing we've both changed for each other over the years?",
    "What's a sacrifice we made that turned out to be worth it?",
    "What's a gesture I do that always makes you feel appreciated?"
  ],
  siblings: [
    "Who was the favorite child? 😏",
    "What was the biggest fight we ever had about?",
    "Which of us was more spoiled?",
    "What was our go-to game or activity as kids?",
    "Who got in trouble more often?",
    "What's something we both found hilarious growing up?",
    "Who had the weirdest childhood obsession?",
    "Which TV show or cartoon did we both love?",
    "What's one thing we always argued about?",
    "What's a shared memory that still makes us laugh?",
    "Who's more likely to forget mom's birthday?",
    "Who cleaned the room less — but got away with it?",
    "What's something we bonded over that others wouldn't get?",
    "What's one thing I used to always borrow or steal from you?",
    "What's a moment when we actually teamed up for once?",
    "What's the most ridiculous lie we ever told together?",
    "Who tattled more when we were kids?",
    "What's one toy or item we always fought over?",
    "Who was more dramatic growing up?",
    "What's something I did just to annoy you?",
    "What was your nickname for me (or mine for you)?",
    "Who always claimed the front seat in the car?",
    "What's something I broke and blamed on you?",
    "Who had the weirdest imaginary friend or game?",
    "What's something we were never allowed to do — but did anyway?",
    "Who would win in a food fight — and why?",
    "What's a childhood secret we still haven't told our parents?",
    "Who faked being sick to skip school more often?",
    "What's a song that instantly reminds you of our childhood?",
    "Who was more likely to start crying just to win?",
    "What's something we both feared as kids?",
    "Who had the better birthday parties?",
    "What's one prank we pulled on each other that went too far?",
    "Who was more likely to sneak snacks into their room?",
    "What's a weird phase we both went through?",
    "Who made the better excuses when caught doing something wrong?",
    "What's one thing we always competed about?",
    "Who had the cooler room growing up?",
    "What's the most embarrassing thing I've seen you do?",
    "Who had the most questionable fashion choices?",
    "What's one moment where we truly had each other's backs?",
    "Who was better at lying to get out of chores?",
    "What's a toy/game we both secretly miss?",
    "Who was more likely to get away with murder (metaphorically)?",
    "What's one inside joke that no one else understands?",
    "What was our worst team-up plan ever?",
    "Who could make the other laugh during serious moments?",
    "What's something silly that always made us laugh uncontrollably?",
    "What's one memory that always gets told at family gatherings?",
    "Who was the sneaky one — and who was the loud one?",
    "Who got the better gifts at holidays (be honest)?",
    "What's something I used to hide from you (or you hid from me)?",
    "What's one thing I copied from you growing up?",
    "Who had the better grades — and who cared less?",
    "What's one way we're completely opposite?",
    "What's one thing we always teamed up to do behind our parents' back?",
    "Who would survive longer on a desert island — and how?",
    "What's one fashion trend we BOTH regret?",
    "Who's more likely to start a dance battle in the living room?",
    "What's something we'd both get grounded for if it came out today?",
    "Who's the better liar — and who's the worse actor?",
    "What's something you wish we still did together like old times?",
    "Who's more likely to hold a grudge over something dumb?",
    "What's the one family dish we always fought over at dinner?",
    "What's a core memory only we would remember?",
    "What's the funniest way we ever got caught doing something bad?"
  ]
};

const questionsMap = {
  1: { label: '💞 Lovers', questions: 'lovers' },
  2: { label: '👯‍♂️ Best Friends', questions: 'bestFriends' },
  3: { label: '👨‍👩‍👧 Mom or Dad', questions: 'momOrDad' },
  4: { label: '👩‍👧‍👧 Siblings', questions: 'siblings' },
  5: { label: '💪 Bros', questions: 'bros' },
  6: { label: '👩 Sisters', questions: 'sisters' },
  7: { label: '🏠 Roommates', questions: 'roommates' },
  8: { label: '💼 Work Buddies', questions: 'workBuddies' },
  9: { label: '💍 Newlyweds', questions: 'newlyweds' },
  10: { label: '👫 Married Couple', questions: 'marriedCouple' }
};
